export const FETCH_DOGS_START = 'FETCH_DOGS_START';
export const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
export const FETCH_DOGS_FAIL = 'FETCH_DOGS_FAIL';

export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAIL = 'FETCH_IMAGES_FAIL';

export const SET_BREED_START = 'SET_BREED_START';
export const SET_BREED_SUCCESS = 'SET_BREED_SUCCESS';
export const SET_BREED_FAIL = 'SET_BREED_FAIL';

export const SET_COUNTER = 'SET_COUNTER';
